# -*- coding: utf-8 -*-
"""traffic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yhM2nsw35CbnchByklQfytedlyrarLy
"""



"""Installing pakages"""

import numpy as np
import h5py
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,GRU, Dense
from sklearn.model_selection import train_test_split

"""Load Dataset"""

file_path = "/content/drive/MyDrive/metr-la.h5"  # update path if needed

with h5py.File(file_path, "r") as f:
    print("Keys:", list(f.keys()))
    data = f['df']['block0_values'][:]

print("Shape:", data.shape)

"""Preprocessing"""

data = np.nan_to_num(data)

"""Normalize Data"""

mean = data.mean()
std = data.std()

data = (data - mean) / std

"""Create sequence"""

def create_sequences(data, seq_len=12):
    X, y = [], []
    for i in range(len(data) - seq_len):
        X.append(data[i:i+seq_len])
        y.append(data[i+seq_len])
    return np.array(X), np.array(y)

seq_len = 12
X, y = create_sequences(data, seq_len)

print("X shape:", X.shape)
print("y shape:", y.shape)

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

"""Build LSTM Model"""

# model = Sequential([
#     LSTM(64, input_shape=(seq_len, X.shape[2])),
#     Dense(X.shape[2])
# ])

model = Sequential([
    GRU(64, input_shape=(seq_len, X.shape[2])),
    Dense(X.shape[2])
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=[
        'mae',
        'mape',
        tf.keras.metrics.RootMeanSquaredError(name='rmse'),
        tf.keras.metrics.R2Score(name='r2'),
        tf.keras.metrics.CosineSimilarity(name='cosine')
    ]
)

model.summary()


model.summary()

"""Train model"""

history = model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.1
)

"""Evaluate Model"""

results = model.evaluate(X_test, y_test)


for name, value in zip(model.metrics_names, results):
    print(f"Test {name}: {value:.4f}")

"""Prediction"""

y_pred = model.predict(X_test)

"""*Visualize* for 1 sensor"""

sensor_id = 181  # change sensor index

plt.figure(figsize=(10,5))
plt.plot(y_test[:100, sensor_id], label="Actual")
plt.plot(y_pred[:100, sensor_id], label="Predicted")
plt.legend()
plt.title("Traffic Prediction (Sensor {})".format(sensor_id))
plt.show()

"""Savin model"""

model.save("metr_gru_model.keras")